# Generated by Django 5.0.6 on 2024-07-06 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retro_gaming', '0002_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
