# Generated by Django 5.0.6 on 2024-08-09 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retro_gaming', '0004_rename_content_juego_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='CANT_JUGADORES',
            field=models.CharField(default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='juego',
            name='FECHA',
            field=models.DateField(default='2000-02-2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='juego',
            name='GENERO',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='juego',
            name='IMAGEN',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='juego',
            name='PESO',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
