# Generated by Django 5.0.6 on 2024-08-13 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retro_gaming', '0005_juego_cant_jugadores_juego_fecha_juego_genero_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JUEGOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOMBRE', models.CharField(max_length=250)),
                ('DESCRIPCION', models.TextField(default='')),
                ('IMAGEN', models.TextField(default='')),
                ('CANT_JUGADORES', models.CharField(max_length=2)),
                ('PESO', models.CharField(max_length=10)),
                ('GENERO', models.CharField(max_length=20)),
                ('FECHA', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Juego',
        ),
    ]
