# Generated by Django 5.0.6 on 2024-08-30 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retro_gaming', '0006_juegos_delete_juego'),
    ]

    operations = [
        migrations.AddField(
            model_name='juegos',
            name='PREMIOS',
            field=models.TextField(default=''),
        ),
    ]
