# Generated by Django 5.0.6 on 2024-09-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retro_gaming', '0007_juegos_premios'),
    ]

    operations = [
        migrations.AddField(
            model_name='juegos',
            name='rating',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
